---
ignore: |
  codeql-analysis.yml
  linter.yml
  npm-grunt.yml
  /node_modules/
  /web/

yaml-files:
  - '.*.yml'
  - '*.yaml'
  - '*.yml'

extends: default

rules:
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  indentation:
    spaces: consistent
    indent-sequences: consistent
    check-multi-line-strings: false
  line-length:
    max: 92
    level: warning
