---
name: Lint Code Base
on:
  push:
    branches: [main, hotfix]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # Checkout the code base
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # install plugins globally to avoid changing package-lock.json
      - name: Install devDependencies
        run: npm install

      # Run Linter against code base
      - name: Lint Code Base with env
        uses: github/super-linter/slim@v4
        env:
          ACTIONS_RUNNER_DEBUG: false
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: web/.*.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: NOTICE
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
