---
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps
    steps:
      # Checkout the code base
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # install plugins
      - name: Install ESLint Plugins
        run: npm install eslint-plugin-compat@latest eslint-plugin-no-storage@latest eslint-plugin-no-unsanitized@latest eslint-plugin-security@latest eslint-plugin-xss@latest eslint-plugin-yml@latest --save-dev

      # Run Linter against code base
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*web/.*.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: NOTICE
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
